# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('StudentName', models.CharField(max_length=200)),
                ('degree', multiselectfield.db.fields.MultiSelectField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Faculty/Staff', 'Faculty/Staff'), ('Certificate', 'Certificate')], max_length=47)),
                ('SchoolName', multiselectfield.db.fields.MultiSelectField(choices=[('SAS', 'School of Arts and Sciences'), ('SE', 'School of Engineering'), ('Fletcher', 'The Fletcher School of Law and Diplomacy'), ('Friedman', 'Gerald J. and Dorothy R. Friedman School of Nutrition Science and Policy'), ('Cummings', 'Cummings School of Veterinary Medicine'), ('Med', 'School of Medicine'), ('Dental', 'School of Dental Medicine'), ('Feinstein', 'Feinstein International Center'), ('PubSafety', 'Public Safety'), ('TIE', 'Tufts Institute for the Environment'), ('Other', 'Other')], max_length=74)),
                ('DepartmentName', multiselectfield.db.fields.MultiSelectField(choices=[('AMER', 'American Studies'), ('ANTH', 'Anthropology'), ('ARC', 'Archaeology'), ('ARCH', 'Architectural Studies'), ('BIO', 'Biology'), ('BIOPSYCH', 'Biopsychology'), ('CD', 'Child Study and Human Development'), ('CHN', 'Chinese'), ('CEE', 'Civil and Environmental Engineering'), ('CLA', 'Classics'), ('CH', 'Community Health'), ('CS', 'Computer Science'), ('CONS', 'Conservation Medicine'), ('EOS', 'Earth and Ocean Studies'), ('ECON', 'Economics'), ('ENG_PHYS', 'Engineering Physics'), ('ENG_SCI', 'Engineering Science'), ('ENG', 'English'), ('ELS', 'Entrepreneurial Leadership'), ('FR', 'French'), ('HIS', 'History'), ('IR', 'International Relations'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MUS', 'Music'), ('PJS', 'Peace and Justice Studies'), ('PHIL', 'Philosophy'), ('PHY', 'Physics'), ('PS', 'Political Science'), ('PSY', 'Psychology'), ('PH', 'Public Health'), ('REE', 'Russian and Eastern European Studies'), ('SOC', 'Sociology'), ('SPN', 'Spanish'), ('STATS', 'Statistics'), ('TTS', 'Tufts Technology Services'), ('UEP', 'Urban and Environmental Policy and Planning (UEP'), ('Other', 'Other')], max_length=168)),
                ('Course', models.CharField(choices=[('GIS 101/ ENV 107/ INTR 81: Introduction to Geographic Information Systems', 'GIS 101/ ENV 107/ INTR 81: Introduction to Geographic Information Systems'), ('UEP 0232: Intro to GIS- GIS for Urban Analysis', 'UEP 0232: Intro to GIS- GIS for Urban Analysis'), ('GIS 102/ UEP 29422/ ENV 197: Advanced Geographic Information Systems', 'GIS 102/ UEP 29422/ ENV 197: Advanced Geographic Information Systems'), ('Fletcher DHP P207: GIS for International Applications', 'Fletcher DHP P207: GIS for International Applications'), ('CEE 187: Geographic Information Systems', 'CEE 187: Geographic Information Systems'), ('NUTR 231: Fundamentals of GIS for Food, Agriculture, and Environmental Applications', 'NUTR 231: Fundamentals of GIS for Food, Agriculture, and Environmental Applications'), ('EOS 104: Geological Applications of GIS', 'EOS 104: Geological Applications of GIS'), ('CEE 194A: Introduction to Remote Sensing', 'CEE 194A: Introduction to Remote Sensing'), ('PH 0262: GIS for Public Health', 'PH 0262: GIS for Public Health'), ('MCM 1009: GIS for Conservation Medicine', 'MCM 1009: GIS for Conservation Medicine'), ('Not enrolled in a GIS Course', 'Not enrolled in a GIS Course'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
