# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Course',
            field=models.CharField(choices=[('GIS 101/ ENV 107/ INTR 81: Introduction to Geographic Information Systems', 'GIS 101/ ENV 107/ INTR 81: Introduction to Geographic Information Systems'), ('UEP 0232: Intro to GIS- GIS for Urban Analysis', 'UEP 0232: Intro to GIS- GIS for Urban Analysis'), ('GIS 102/ UEP 29422/ ENV 197: Advanced Geographic Information Systems', 'GIS 102/ UEP 29422/ ENV 197: Advanced Geographic Information Systems'), ('Fletcher DHP P207: GIS for International Applications', 'Fletcher DHP P207: GIS for International Applications'), ('CEE 187: Geographic Information Systems', 'CEE 187: Geographic Information Systems'), ('NUTR 231: Fundamentals of GIS for Food, Agriculture, and Environmental Applications', 'NUTR 231: Fundamentals of GIS for Food, Agriculture, and Environmental Applications'), ('EOS 104: Geological Applications of GIS', 'EOS 104: Geological Applications of GIS'), ('CEE 194A: Introduction to Remote Sensing', 'CEE 194A: Introduction to Remote Sensing'), ('PH 0262: GIS for Public Health', 'PH 0262: GIS for Public Health'), ('MCM 1009: GIS for Conservation Medicine', 'MCM 1009: GIS for Conservation Medicine'), ('Not enrolled in a GIS Course', 'Not enrolled in a GIS Course'), ('Other', 'Other')], max_length=200, verbose_name='GIS Course'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='DepartmentName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AMER', 'American Studies'), ('ANTH', 'Anthropology'), ('ARC', 'Archaeology'), ('ARCH', 'Architectural Studies'), ('BIO', 'Biology'), ('BIOPSYCH', 'Biopsychology'), ('CD', 'Child Study and Human Development'), ('CHN', 'Chinese'), ('CEE', 'Civil and Environmental Engineering'), ('CLA', 'Classics'), ('CH', 'Community Health'), ('CS', 'Computer Science'), ('CONS', 'Conservation Medicine'), ('EOS', 'Earth and Ocean Studies'), ('ECON', 'Economics'), ('ENG_PHYS', 'Engineering Physics'), ('ENG_SCI', 'Engineering Science'), ('ENG', 'English'), ('ELS', 'Entrepreneurial Leadership'), ('FR', 'French'), ('HIS', 'History'), ('IR', 'International Relations'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MUS', 'Music'), ('PJS', 'Peace and Justice Studies'), ('PHIL', 'Philosophy'), ('PHY', 'Physics'), ('PS', 'Political Science'), ('PSY', 'Psychology'), ('PH', 'Public Health'), ('REE', 'Russian and Eastern European Studies'), ('SOC', 'Sociology'), ('SPN', 'Spanish'), ('STATS', 'Statistics'), ('TTS', 'Tufts Technology Services'), ('UEP', 'Urban and Environmental Policy and Planning (UEP'), ('Other', 'Other')], max_length=168, verbose_name="Student's Department(s)"),
        ),
        migrations.AlterField(
            model_name='poster',
            name='FullPosterTitle',
            field=models.CharField(max_length=200, verbose_name='Title of GIS Poster?'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='PlaceKeywordGeonames',
            field=models.CharField(max_length=200, verbose_name='Place Keywords - Where is your GIS project located?'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='PosterPath',
            field=models.CharField(default='pass', max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ReleaseForm',
            field=models.BooleanField(verbose_name='Website Release Form'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='SDrivePathway',
            field=models.CharField(default='pass', max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='SchoolName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SAS', 'School of Arts and Sciences'), ('SE', 'School of Engineering'), ('Fletcher', 'The Fletcher School of Law and Diplomacy'), ('Friedman', 'Gerald J. and Dorothy R. Friedman School of Nutrition Science and Policy'), ('Cummings', 'Cummings School of Veterinary Medicine'), ('Med', 'School of Medicine'), ('Dental', 'School of Dental Medicine'), ('Feinstein', 'Feinstein International Center'), ('PubSafety', 'Public Safety'), ('TIE', 'Tufts Institute for the Environment'), ('Other', 'Other')], max_length=74, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='StudentName',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='First Name'), max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AWB', 'Animal, Wildlife and Biota'), ('AEC', 'Architecture, Engineering and Construction'), ('BC', 'Business and Commercial'), ('CD', 'Community Development'), ('DI', 'Defense and Intelligence'), ('EDU', 'Education'), ('EC', 'Energy and Climate'), ('ER', 'Exposure and Risk'), ('FAC', 'Facilities'), ('FD', 'Finance and Development'), ('GOV', 'Government'), ('HLT', 'Health'), ('HUM', 'Humanities'), ('HA', 'Humanitarian Assistance'), ('INF', 'Infrastructure'), ('NR', 'Natural Resources'), ('NUTR', 'Nutrition'), ('PS', 'Public Safety'), ('REC', 'Recreation'), ('TRS', 'Transportation'), ('WAT', 'Water')], max_length=75, verbose_name='Topic Keyword'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Air and Atmosphere', 'Air and Atmosphere'), ('Accessibility', 'Accessibility'), ('Agriculture', 'Agriculture'), ('Alternative and Renewable Energy', 'Alternative and Renewable Energy'), ('Animal Health', 'Animal Health'), ('Archeology', 'Archeology'), ('Aviation', 'Aviation'), ('Banking and Financial Services', 'Banking and Financial Services'), ('Building and Landscape Architecture', 'Building and Landscape Architecture'), ('Census', 'Census'), ('City Management', 'City Management'), ('Climate and Weather', 'Climate and Weather'), ('Climate Change', 'Climate Change'), ('Community Advocacy', 'Community Advocacy'), ('Community Analysis', 'Community Analysis'), ('Community Maps', 'Community Maps'), ('Conflict', 'Conflict'), ('Conservation', 'Conservation'), ('Construction', 'Construction'), ('Contamination', 'Contamination'), ('Criminal Justice', 'Criminal Justice'), ('Cultural Resource Management', 'Cultural Resource Management'), ('Disease', 'Disease'), ('Ecology', 'Ecology'), ('Economic Development', 'Economic Development'), ('Elections', 'Elections'), ('Electric Utilities', 'Electric Utilities'), ('EMS and Emergency Calls', 'EMS and Emergency Calls'), ('Emergency Management', 'Emergency Management'), ('Energy', 'Energy'), ('Energy Planning', 'Energy Planning'), ('Engineering and Design', 'Engineering and Design'), ('Environmental Justice', 'Environmental Justice'), ('Environmental Management', 'Environmental Management'), ('Federal Agencies', 'Federal Agencies'), ('Fire Management', 'Fire Management'), ('Fire Rescue', 'Fire Rescue'), ('Fisheries', 'Fisheries'), ('Flood Management', 'Flood Management'), ('Food Access', 'Food Access'), ('Food Deserts', 'Food Deserts'), ('Food Insecurity', 'Food Insecurity'), ('Food Production', 'Food Production'), ('Forestry', 'Forestry'), ('Gentrification', 'Gentrification'), ('Geosciences', 'Geosciences'), ('Groundwater', 'Groundwater'), ('Hazard management', 'Hazard management'), ('Health Systems', 'Health Systems'), ('Highways and Roads', 'Highways and Roads'), ('History', 'History'), ('Homeland Security', 'Homeland Security'), ('Hospitals', 'Hospitals'), ('Housing', 'Housing'), ('Human Security', 'Human Security'), ('Human Services', 'Human Services'), ('Humanitarian Aid and Relief', 'Humanitarian Aid and Relief'), ('Hydraulic Engineering', 'Hydraulic Engineering'), ('Intelligence', 'Intelligence'), ('International Development', 'International Development'), ('Land Administration', 'Land Administration'), ('Law Enforcement', 'Law Enforcement'), ('Local Government', 'Local Government'), ('Location Based Services', 'Location Based Services'), ('Manufacturing', 'Manufacturing'), ('Medicine', 'Medicine'), ('Military Operations', 'Military Operations'), ('Mining', 'Mining'), ('National Security', 'National Security'), ('Natural Disasters', 'Natural Disasters'), ('Oceans and Maritime', 'Oceans and Maritime'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Parks and Natural Resources', 'Parks and Natural Resources'), ('Petroleum and Fossil Fuels', 'Petroleum and Fossil Fuels'), ('Physical Activity', 'Physical Activity'), ('Pipeline and Gas Utilities', 'Pipeline and Gas Utilities'), ('Policy', 'Policy'), ('Pollution', 'Pollution'), ('Poverty Mapping', 'Poverty Mapping'), ('Public Health', 'Public Health'), ('Public Transit', 'Public Transit'), ('Public Works', 'Public Works'), ('Railways', 'Railways'), ('Real Estate', 'Real Estate'), ('Redistricting', 'Redistricting'), ('Regional Planning', 'Regional Planning'), ('Retail', 'Retail'), ('Risk Assessment', 'Risk Assessment'), ('Safety and Security', 'Safety and Security'), ('Schools', 'Schools'), ('Sea Level Rise', 'Sea Level Rise'), ('Social Inequality', 'Social Inequality'), ('State Government', 'State Government'), ('Storm Water', 'Storm Water'), ('Subsidized Housing', 'Subsidized Housing'), ('Surveying', 'Surveying'), ('Sustainability', 'Sustainability'), ('Telecommunications', 'Telecommunications'), ('Universities and Colleges', 'Universities and Colleges'), ('Urban Planning', 'Urban Planning'), ('Urbanization', 'Urbanization'), ('Wastewater', 'Wastewater'), ('Water Management', 'Water Management'), ('Water Quality', 'Water Quality'), ('Water Quantity', 'Water Quantity'), ('Water Resources', 'Water Resources'), ('Wildlife Management', 'Wildlife Management')], max_length=1741, verbose_name='Sub-Topic Keyword'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Best Path - Least Cost', 'Best Path - Least Cost'), ('Change Detection', 'Change Detection'), ('Hydro Analysis', 'Hydro Analysis'), ('Needs Analysis', 'Needs Analysis'), ('Network Analysis', 'Network Analysis'), ('Proximity Analysis', 'Proximity Analysis'), ('Remote Sensing', 'Remote Sensing'), ('Statistics/Spatial Statistics', 'Statistics/Spatial Statistics'), ('Suitability Analysis', 'Suitability Analysis'), ('Thematic Mapping', 'Thematic Mapping'), ('Vulnerability Analysis', 'Vulnerability Analysis')], max_length=211, verbose_name='Methodological Keyword'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThumbnailName',
            field=models.CharField(default='pass', max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThumbnailPath',
            field=models.CharField(default='pass', max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
    ]
