# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0002_auto_20171027_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='Approved',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='poster',
            name='PosterWinner',
            field=models.BooleanField(default='False', verbose_name='Poster Winner'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Course',
            field=models.CharField(choices=[('GIS101', 'GIS 101/ ENV 107/ INTR 81: Introduction to Geographic Information Systems'), ('UEP232', 'UEP 0232: Intro to GIS- GIS for Urban Analysis'), ('GIS 102', 'GIS 102/ UEP 29422/ ENV 197: Advanced Geographic Information Systems'), ('DHP207', 'Fletcher DHP P207: GIS for International Applications'), ('CEE187', 'CEE 187: Geographic Information Systems'), ('NUTR0231', 'NUTR 231: Fundamentals of GIS for Food, Agriculture, and Environmental Applications'), ('EOS104', 'EOS 104: Geological Applications of GIS'), ('CEE194', 'CEE 194A: Introduction to Remote Sensing'), ('PH262', 'PH 0262: GIS for Public Health'), ('MCM1009', 'MCM 1009: GIS for Conservation Medicine'), ('Not enrolled in a GIS Course', 'Not enrolled in a GIS Course'), ('Other', 'Other')], max_length=200, verbose_name='GIS Course'),
        ),
    ]
