# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0003_auto_20171114_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='Course',
            new_name='Course_name',
        ),
        migrations.AlterField(
            model_name='poster',
            name='Dept_code',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='First Name'), max_length=200),
        ),
    ]
