# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0004_auto_20171114_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='Course_code',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='First Name'), max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Dept_code',
            field=models.CharField(max_length=200),
        ),
    ]
