# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0005_auto_20171114_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
