# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0006_auto_20171114_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='Approved',
            new_name='release',
        ),
        migrations.AlterField(
            model_name='poster',
            name='Course_code',
            field=models.CharField(max_length=200),
        ),
    ]
