# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0007_auto_20171116_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='release',
            new_name='release_form',
        ),
        migrations.AddField(
            model_name='poster',
            name='reviewed',
            field=models.BooleanField(default='False', verbose_name='good?'),
        ),
    ]
