# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0008_auto_20171117_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='reviewed',
            field=models.BooleanField(default='False'),
        ),
    ]
