# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0009_auto_20171128_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='image',
            new_name='PDFPoster',
        ),
    ]
