# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0010_auto_20171128_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='PDFPoster',
            field=models.FileField(upload_to='images', verbose_name='PDF of Poster'),
        ),
    ]
