# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0011_auto_20171128_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='ranking',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='poster',
            name='StudentName',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name="Student's First Name"), max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='degree',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Faculty/Staff', 'Faculty/Staff'), ('Certificate', 'Certificate')], max_length=47, verbose_name="Student's Degree"),
        ),
        migrations.AlterField(
            model_name='poster',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name="Student's First Name"),
        ),
        migrations.AlterField(
            model_name='poster',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name="Student's Last Name"),
        ),
    ]
