# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0015_auto_20171128_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GIS_Poster.Course', verbose_name='GIS Course'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='DepartmentName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AMER', 'American Studies'), ('ANTH', 'Anthropology'), ('ARC', 'Archaeology'), ('ARCH', 'Architectural Studies'), ('BIO', 'Biology'), ('BIOPSYCH', 'Biopsychology'), ('CD', 'Child Study and Human Development'), ('CHN', 'Chinese'), ('CEE', 'Civil and Environmental Engineering'), ('CLA', 'Classics'), ('CH', 'Community Health'), ('CS', 'Computer Science'), ('CONS', 'Conservation Medicine'), ('EOS', 'Earth and Ocean Studies'), ('ECON', 'Economics'), ('ENG_PHYS', 'Engineering Physics'), ('ENG_SCI', 'Engineering Science'), ('ENG', 'English'), ('ELS', 'Entrepreneurial Leadership'), ('FR', 'French'), ('HIS', 'History'), ('IR', 'International Relations'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MUS', 'Music'), ('PJS', 'Peace and Justice Studies'), ('PHIL', 'Philosophy'), ('PHY', 'Physics'), ('PS', 'Political Science'), ('PSY', 'Psychology'), ('PH', 'Public Health'), ('REE', 'Russian and Eastern European Studies'), ('SOC', 'Sociology'), ('SPN', 'Spanish'), ('STATS', 'Statistics'), ('TTS', 'Tufts Technology Services'), ('UEP', 'Urban and Environmental Policy and Planning (UEP)'), ('Other', 'Other')], max_length=168, verbose_name="Student's Department(s)"),
        ),
        migrations.AlterField(
            model_name='poster',
            name='FullPosterTitle',
            field=models.CharField(max_length=200, verbose_name='Title of GIS Poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='PlaceKeywordGeonames',
            field=models.CharField(max_length=200, verbose_name='Place Keywords - Where is your GIS Project located'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='SchoolName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SAS', 'School of Arts and Sciences'), ('SE', 'School of Engineering'), ('Fletcher', 'The Fletcher School of Law and Diplomacy'), ('Friedman', 'Gerald J. and Dorothy R. Friedman School of Nutrition Science and Policy'), ('Cummings', 'Cummings School of Veterinary Medicine'), ('Med', 'School of Medicine'), ('Dental', 'School of Dental Medicine'), ('Feinstein', 'Feinstein International Center'), ('PubSafety', 'Public Safety'), ('TIE', 'Tufts Institute for the Environment'), ('Other', 'Other')], max_length=74, verbose_name='School Name?'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=20, verbose_name='Semester'),
        ),
    ]
