# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0016_auto_20171208_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='ReleaseForm',
        ),
        migrations.AlterField(
            model_name='poster',
            name='release_form',
            field=models.BooleanField(verbose_name='Website Release Form'),
        ),
    ]
