# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0017_auto_20171215_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='release_form',
            field=models.CharField(default='', max_length=15),
        ),
    ]
