# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0018_auto_20171215_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='Course_name',
        ),
    ]
