# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0019_remove_poster_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Dept',
            field=models.CharField(default='Rect', max_length=200),
        ),
    ]
