# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0021_poster_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Dept',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Course_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GIS_Poster.Course', verbose_name='GIS Course'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018')], max_length=20),
        ),
    ]
