# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0022_auto_20180131_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GIS_Poster.Course', verbose_name='GIS Course'),
        ),
    ]
