# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0025_auto_20180201_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='PDFPoster',
            field=models.FileField(upload_to='Pdf_path', verbose_name='PDF of Poster'),
        ),
    ]
