# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 17:15
from __future__ import unicode_literals

import GIS_Poster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0026_auto_20180201_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='PDFPoster',
            field=models.FileField(max_length=500, upload_to=GIS_Poster.models.Poster.upload_path_handler, verbose_name='PDF of Poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='SDrivePathway',
            field=models.CharField(default='pass', max_length=1000),
        ),
    ]
