# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0027_auto_20180202_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='Course_code',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='Dept_code',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='Year_range',
        ),
    ]
