# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0028_auto_20180208_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='release_signature',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='poster',
            name='release_form',
            field=models.CharField(default='', max_length=250),
        ),
    ]
