# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0030_remove_poster_release_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='AcademicYear',
            field=models.CharField(default='', max_length=200),
        ),
    ]
