# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_Poster', '0031_poster_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='JobElist',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='DepartmentName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'Not-Applicable'), ('AFR', 'Africana Studies'), ('AMER', 'American Studies'), ('ANTH', 'Anthropology'), ('ARB', 'Arabic'), ('ARCH', 'Archaeology'), ('FAH', 'Art and Art History'), ('AAST', 'Asian American Studies'), ('BIO', 'Biology'), ('BIOE', 'Bioengineering'), ('BME', 'Biomedical Engineering'), ('CHBE', 'Chemical and Biological Engineering'), ('CHEM', 'Chemistry'), ('CD', 'Child Study and Human Development'), ('CHN', 'Chinese'), ('CEE', 'Civil and Environmental Engineering'), ('CEE', 'Civic Studies'), ('CLS', 'Classics'), ('CEE', 'Colonialism Studies'), ('CH', 'Community Health'), ('CS', 'Computer Science'), ('CIS', 'Center for Interdisciplinary Studies'), ('DRA', 'Drama and Dance'), ('EOS', 'Earth and Ocean Studies'), ('ECON', 'Economics'), ('ED', 'Education'), ('ECE', 'Electrical and Computer Engineering'), ('ENG_PHYS', 'Engineering Physics'), ('ENG_SCI', 'Engineering Science'), ('ENG', 'English'), ('ELS', 'Entrepreneurial Leadership'), ('ES', 'Environmental Studies'), ('FMS', 'Film and Media Studies'), ('FR', 'French'), ('HIS', 'History'), ('IR', 'International Relations'), ('JS', 'Judaic Studies'), ('LAS', 'Latin American Studies'), ('LS', 'Latino Studies'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MUS', 'Music'), ('PJS', 'Peace and Justice Studies'), ('PHIL', 'Philosophy'), ('PHY', 'Physics and Astronomy'), ('PS', 'Political Science'), ('PSY', 'Psychology'), ('PH', 'Public Health'), ('RLG', 'Religion'), ('REE', 'Russian and Eastern European Studies'), ('SOC', 'Sociology'), ('SPN', 'Spanish'), ('STATS', 'Statistics'), ('TTS', 'Tufts Technology Services'), ('TIE', 'Tufts Institute for the Environment'), ('UEP', 'Urban and Environmental Policy and Planning (UEP)'), ('WGS', "Women's, Gender, and Sexuality Studies"), ('Other', 'Other')], max_length=241, verbose_name="Student's Department(s)"),
        ),
        migrations.AlterField(
            model_name='poster',
            name='SchoolName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SAS', 'School of Arts and Sciences'), ('SE', 'School of Engineering'), ('Fletcher', 'The Fletcher School of Law and Diplomacy'), ('Friedman', 'Gerald J. and Dorothy R. Friedman School of Nutrition Science and Policy'), ('Cummings', 'Cummings School of Veterinary Medicine'), ('Med', 'School of Medicine'), ('Dental', 'School of Dental Medicine'), ('Feinstein', 'Feinstein International Center'), ('PubSafety', 'Public Safety'), ('Other', 'Other')], max_length=70, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='StudentName',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='First Name'), max_length=200),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AWB', 'Animal, Wildlife and Biota'), ('AEC', 'Architecture, Engineering and Construction'), ('BC', 'Business and Commercial'), ('CD', 'Community Development'), ('DI', 'Defense and Intelligence'), ('EDU', 'Education'), ('EC', 'Energy and Climate'), ('ER', 'Exposure and Risk'), ('FAC', 'Facilities'), ('FD', 'Finance and Development'), ('GOV', 'Government'), ('HLT', 'Health'), ('HUM', 'Humanities'), ('HA', 'Humanitarian Assistance'), ('INF', 'Infrastructure'), ('NR', 'Natural Resources'), ('NUTR', 'Nutrition'), ('PS', 'Public Safety'), ('REC', 'Recreation'), ('TRS', 'Transportation'), ('WAT', 'Water')], max_length=75, verbose_name='Topic Keyword(s)'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Air and Atmosphere', 'Air and Atmosphere'), ('Accessibility', 'Accessibility'), ('Agriculture', 'Agriculture'), ('Alternative and Renewable Energy', 'Alternative and Renewable Energy'), ('Animal Health', 'Animal Health'), ('Archeology', 'Archeology'), ('Aviation', 'Aviation'), ('Banking and Financial Services', 'Banking and Financial Services'), ('Building and Landscape Architecture', 'Building and Landscape Architecture'), ('Census', 'Census'), ('City Management', 'City Management'), ('Climate and Weather', 'Climate and Weather'), ('Climate Change', 'Climate Change'), ('Community Advocacy', 'Community Advocacy'), ('Community Analysis', 'Community Analysis'), ('Community Maps', 'Community Maps'), ('Conflict', 'Conflict'), ('Conservation', 'Conservation'), ('Construction', 'Construction'), ('Contamination', 'Contamination'), ('Criminal Justice', 'Criminal Justice'), ('Cultural Resource Management', 'Cultural Resource Management'), ('Disease', 'Disease'), ('Ecology', 'Ecology'), ('Economic Development', 'Economic Development'), ('Elections', 'Elections'), ('Electric Utilities', 'Electric Utilities'), ('EMS and Emergency Calls', 'EMS and Emergency Calls'), ('Emergency Management', 'Emergency Management'), ('Energy', 'Energy'), ('Energy Planning', 'Energy Planning'), ('Engineering and Design', 'Engineering and Design'), ('Environmental Justice', 'Environmental Justice'), ('Environmental Management', 'Environmental Management'), ('Federal Agencies', 'Federal Agencies'), ('Fire Management', 'Fire Management'), ('Fire Rescue', 'Fire Rescue'), ('Fisheries', 'Fisheries'), ('Flood Management', 'Flood Management'), ('Food Access', 'Food Access'), ('Food Deserts', 'Food Deserts'), ('Food Insecurity', 'Food Insecurity'), ('Food Production', 'Food Production'), ('Forestry', 'Forestry'), ('Gentrification', 'Gentrification'), ('Geosciences', 'Geosciences'), ('Groundwater', 'Groundwater'), ('Hazard management', 'Hazard management'), ('Health Systems', 'Health Systems'), ('Highways and Roads', 'Highways and Roads'), ('History', 'History'), ('Homeland Security', 'Homeland Security'), ('Hospitals', 'Hospitals'), ('Housing', 'Housing'), ('Human Security', 'Human Security'), ('Human Services', 'Human Services'), ('Humanitarian Aid and Relief', 'Humanitarian Aid and Relief'), ('Hydraulic Engineering', 'Hydraulic Engineering'), ('Intelligence', 'Intelligence'), ('International Development', 'International Development'), ('Land Administration', 'Land Administration'), ('Law Enforcement', 'Law Enforcement'), ('Local Government', 'Local Government'), ('Location Based Services', 'Location Based Services'), ('Manufacturing', 'Manufacturing'), ('Medicine', 'Medicine'), ('Military Operations', 'Military Operations'), ('Mining', 'Mining'), ('National Security', 'National Security'), ('Natural Disasters', 'Natural Disasters'), ('Oceans and Maritime', 'Oceans and Maritime'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Parks and Natural Resources', 'Parks and Natural Resources'), ('Petroleum and Fossil Fuels', 'Petroleum and Fossil Fuels'), ('Physical Activity', 'Physical Activity'), ('Pipeline and Gas Utilities', 'Pipeline and Gas Utilities'), ('Policy', 'Policy'), ('Pollution', 'Pollution'), ('Poverty Mapping', 'Poverty Mapping'), ('Public Health', 'Public Health'), ('Public Transit', 'Public Transit'), ('Public Works', 'Public Works'), ('Railways', 'Railways'), ('Real Estate', 'Real Estate'), ('Redistricting', 'Redistricting'), ('Regional Planning', 'Regional Planning'), ('Retail', 'Retail'), ('Risk Assessment', 'Risk Assessment'), ('Safety and Security', 'Safety and Security'), ('Schools', 'Schools'), ('Sea Level Rise', 'Sea Level Rise'), ('Social Inequality', 'Social Inequality'), ('State Government', 'State Government'), ('Storm Water', 'Storm Water'), ('Subsidized Housing', 'Subsidized Housing'), ('Surveying', 'Surveying'), ('Sustainability', 'Sustainability'), ('Telecommunications', 'Telecommunications'), ('Universities and Colleges', 'Universities and Colleges'), ('Urban Planning', 'Urban Planning'), ('Urbanization', 'Urbanization'), ('Wastewater', 'Wastewater'), ('Water Management', 'Water Management'), ('Water Quality', 'Water Quality'), ('Water Quantity', 'Water Quantity'), ('Water Resources', 'Water Resources'), ('Wildlife Management', 'Wildlife Management')], max_length=1741, verbose_name='Sub-Topic Keyword(s)'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ThemeKeywordL3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Best Path - Least Cost', 'Best Path - Least Cost'), ('Change Detection', 'Change Detection'), ('Hydro Analysis', 'Hydro Analysis'), ('Needs Analysis', 'Needs Analysis'), ('Network Analysis', 'Network Analysis'), ('Proximity Analysis', 'Proximity Analysis'), ('Remote Sensing', 'Remote Sensing'), ('Statistics/Spatial Statistics', 'Statistics/Spatial Statistics'), ('Suitability Analysis', 'Suitability Analysis'), ('Thematic Mapping', 'Thematic Mapping'), ('Vulnerability Analysis', 'Vulnerability Analysis')], max_length=211, verbose_name='Methods'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Year',
            field=models.IntegerField(choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)]),
        ),
        migrations.AlterField(
            model_name='poster',
            name='degree',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Faculty/Staff', 'Faculty/Staff'), ('Certificate', 'Certificate')], max_length=47, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='release_form',
            field=models.CharField(default='', max_length=250, verbose_name='Release ed Form'),
        ),
    ]
